server:
  port: 8085
spring:
  application:
    name: zuul-gateway
ribbon:
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 130000
#eureka:
#  instance:
#    hostname: localhost
#    port: 8761
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#    instance:
#      preferIpAddress: true


zuul:
  #  sensitiveHeaders: Cookie,Set-Cookie
  ribbon:
    eager-load:
      enabled: true
  routes:
    nooble-security:
      sensitiveHeaders:
      path: /oauth/**
      stripPrefix: false
      serviceId: oauth-demo
    morningservice:
      sensitiveHeaders:
      path: /morning/**
      stripPrefix: false
      serviceId: good-morning
    eveningservice:
      sensitiveHeaders:
      path: /evening/**
      stripPrefix: false
      serviceId: good-evening
    afternoonservice:
      sensitiveHeaders:
      path: /noon/**
      stripPrefix: false
      serviceId: good-afternoon


      #      ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
